### ISSUE TITLE
cinematic menu opening after using /cinematic play 

### ISSUE THREAD

**Issue by CaptainSnickerz** [PluginBugs/Issues-CinematicsStudio#38] opened 2023-06-04 01:06 UTC
### Terms

- [X] I'm using the very latest version of CinematicsStudio and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-CinematicsStudio/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://lonedev.gitbook.io/cinematicstudio) to know if a solution is already known.
- [X] I already searched on the **Discord** server to know if anyone already provided a solution in the past for the issue.

### What happened?

cinematic studios opening edit menu after exiting cutscene by using /cinematic play [ cinematic name] [username]
made a video but i think it will only be there a short time

### Steps to reproduce the issue

1. type /cinematic play [cinematic] [username]
2. watch cut scene
3. cutscene ends
3. menu opens with all access available to delete etc

### Server version

This server is running Paper version git-Paper-388 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: fc9ee65 on ver/1.18.2)
You are running the latest version
Previous version: git-Paper-387 (MC: 1.18.2)

### CinematicsStudio Version

1.4.3-r8

### ProtocolLib Version

protocol lib 4.8.0

### LoneLibs Version

lone libs 1.0.24

### FULL server log

no errors. cannot provide full server log due to copyright issues

### CinematicsStudio config.yml

```shell
blank config?
```

**Comment by CaptainSnickerz** [comment] 2023-06-04 01:06
i did try to add a gif but its not working

**Comment by CaptainSnickerz** [comment] 2023-06-04 02:14
https://www.youtube.com/watch?v=Qbl07Jsnt1g

**Comment by CaptainSnickerz** [comment] 2023-06-07 20:21
figured its whenever the player sends the command from console or with op permissions but i dont want players to have access to the command >.<

**Comment by LoneDev6** [comment] 2023-06-08 09:04
Seems a duplicate of this issue https://github.com/PluginBugs/Issues-CinematicsStudio/issues/24 , but this one is more precise.
I'll fix this as soon as possible.

**Comment by CaptainSnickerz** [comment] 2023-06-20 11:21
> Seems a duplicate of this issue #24 , but this one is more precise. I'll fix this as soon as possible.

any way you could give us a rough date? just so i know when to expect you guys :):) im literally checking back every half an hour hahaha

**Comment by LoneDev6** [comment] 2023-06-20 11:23
If I have to be sincere this plugin is not really a priority to me due to the instability of the codebase (I'm not its original author).
In the future I'll recode this completely to avoid this kind of issues.

Anyway expect an update next week.

No need to check it every hour, if you have notifications turned on you will get a notification as soon as I push an update.

**Comment by CaptainSnickerz** [comment] 2023-06-22 06:45
> If I have to be sincere this plugin is not really a priority to me due to the instability of the codebase (I'm not its original author). In the future I'll recode this completely to avoid this kind of issues.
> 
> Anyway expect an update next week.
> 
> No need to check it every hour, if you have notifications turned on you will get a notification as soon as I push an update.

thank you :D:D:D im very very new to using github haha

**Closed** 2023-06-22 14:55 UTC
Labels: bug
